# Generated by Django 2.0.9 on 2018-11-19 20:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tent_pin', models.IntegerField()),
                ('qr_code_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Email address must be a zagmail email address', regex='^\\w{3,15}@zagmail.gonzaga.edu')])),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField(default=-1, unique=True)),
                ('graduation_year', models.IntegerField(default=-1)),
                ('phone_number', models.CharField(blank=True, default=-1, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999-999-9999'", regex='^\\+?1?\\d{3,3}?-?\\d{3,3}?-?\\d{4,4}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenter_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenter_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenter_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenter_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenter_5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenter_6', to=settings.AUTH_USER_MODEL),
        ),
    ]
