# Generated by Django 2.0.9 on 2018-11-26 18:53

import Api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_1',
            field=models.ForeignKey(limit_choices_to=Api.models.limit_tenter_choices, on_delete=django.db.models.deletion.CASCADE, related_name='tenter_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_2',
            field=models.ForeignKey(limit_choices_to=Api.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenter_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_3',
            field=models.ForeignKey(limit_choices_to=Api.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenter_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_4',
            field=models.ForeignKey(limit_choices_to=Api.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenter_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_5',
            field=models.ForeignKey(limit_choices_to=Api.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenter_5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_6',
            field=models.ForeignKey(limit_choices_to=Api.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenter_6', to=settings.AUTH_USER_MODEL),
        ),
    ]
