# Generated by Django 2.0.9 on 2018-11-05 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Email address must be a zagmail email address', regex='^\\w{3,15}@zagmail.gonzaga.edu')]),
        ),
    ]
