# Generated by Django 2.0.9 on 2019-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20181126_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_start', models.DateTimeField()),
                ('tenting_start', models.DateTimeField()),
                ('game_name', models.CharField(max_length=20)),
            ],
        ),
    ]
