# Generated by Django 2.0.9 on 2018-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20181105_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='graduation_year',
            field=models.IntegerField(default=2019, max_length=4),
            preserve_default=False,
        ),
    ]
