# Generated by Django 2.0.9 on 2019-01-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentgroup',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_id', to='Api.Game'),
        ),
    ]
