# Generated by Django 2.0.9 on 2019-01-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_tentgroup_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentgroup',
            name='tent_number',
            field=models.IntegerField(null=True),
        ),
    ]
