# Generated by Django 2.0.9 on 2018-11-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20181110_1352'),
        ('Api', '0004_userprofile_graduation_year'),
    ]

    operations = [
    ]
