# Generated by Django 2.0.9 on 2019-01-20 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_tentgroup_tent_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
