# Generated by Django 2.0.9 on 2018-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_merge_20181117_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='graduation_year',
            field=models.IntegerField(default=-1),
        ),
    ]
