# Generated by Django 2.0.9 on 2019-01-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20190120_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirmation_id',
        ),
    ]
