# Generated by Django 2.0.9 on 2019-01-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_userprofile_confirmation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
