# Generated by Django 2.0.9 on 2019-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tent_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_check', models.BooleanField(default=False)),
                ('setup_check', models.BooleanField(default=False)),
                ('tent_check_1', models.BooleanField(default=False)),
                ('tent_check_2', models.BooleanField(default=False)),
                ('tent_check_3', models.BooleanField(default=False)),
                ('tent_check_4', models.BooleanField(default=False)),
                ('final_check', models.BooleanField(default=False)),
            ],
        ),
    ]
