# Generated by Django 2.0.9 on 2019-03-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tents', '0001_initial'),
        ('Tent_Checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent_check',
            name='tent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tents.TentGroup'),
        ),
    ]
