# Generated by Django 2.0.9 on 2019-03-20 19:57

import Tents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_1',
            field=models.ForeignKey(limit_choices_to=Tents.models.limit_tenter_choices, on_delete=django.db.models.deletion.PROTECT, related_name='tenter_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_2',
            field=models.ForeignKey(limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_3',
            field=models.ForeignKey(limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_4',
            field=models.ForeignKey(limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_5',
            field=models.ForeignKey(limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentgroup',
            name='tenter_6',
            field=models.ForeignKey(limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_6', to=settings.AUTH_USER_MODEL),
        ),
    ]
