# Generated by Django 2.0.9 on 2019-04-17 04:19

import Tents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tents', '0002_auto_20190320_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_2',
            field=models.ForeignKey(blank=True, limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_3',
            field=models.ForeignKey(blank=True, limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_4',
            field=models.ForeignKey(blank=True, limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_5',
            field=models.ForeignKey(blank=True, limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tenter_6',
            field=models.ForeignKey(blank=True, limit_choices_to=Tents.models.limit_tenter_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenter_6', to=settings.AUTH_USER_MODEL),
        ),
    ]
