# Generated by Django 2.0.9 on 2019-04-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tents', '0003_auto_20190416_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentgroup',
            name='game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_id', to='Game.Game'),
        ),
        migrations.AlterField(
            model_name='tentgroup',
            name='tent_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
