# Generated by Django 2.0.9 on 2018-11-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20181103_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default=5555555555, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
