# Generated by Django 2.0.9 on 2018-11-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20181103_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
