# Generated by Django 2.0.9 on 2018-11-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20181103_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
