# Generated by Django 2.0.9 on 2018-11-05 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20181103_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Email address must be a zagmail email address', regex='^\\w{3,15}@zagmail.gonzaga.edu')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default=-1, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999-999-9999'", regex='^\\+?1?\\d{3,3}?-?\\d{3,3}?-?\\d{4,4}$')]),
        ),
    ]
